# Generated by Django 5.1.7 on 2025-03-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_demo_app', '0003_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
