# Generated by Django 5.1.7 on 2025-03-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_demo_app', '0004_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
